CREATE TABLE "DB2ADMIN"."USER_PROFILE" (
		"UP_USERID" VARCHAR(15 OCTETS) NOT NULL, 
		"UPTOKEN" CHAR(174 OCTETS) NOT NULL, 
		"UP_HOME_MARKET" SMALLINT NOT NULL, 
		"UP_FIRST_NAME" VARCHAR(25 OCTETS) NOT NULL, 
		"UP_LAST_NAME" VARCHAR(25 OCTETS) NOT NULL, 
		"UP_ADDRESS1" VARCHAR(50 OCTETS) NOT NULL, 
		"UP_ADDRESS2" VARCHAR(50 OCTETS), 
		"UP_CITY" VARCHAR(50 OCTETS) NOT NULL, 
		"UP_STATE" CHAR(2 OCTETS) NOT NULL, 
		"UP_ZIP" CHAR(5 OCTETS) NOT NULL, 
		"UP_ZIP4" CHAR(4 OCTETS), 
		"UP_PHONE" VARCHAR(14 OCTETS) NOT NULL, 
		"UP_FAX" VARCHAR(14 OCTETS), 
		"UP_EMAIL" VARCHAR(64 OCTETS), 
		"UPSSN" CHAR(11 OCTETS) NOT NULL, 
		"UPDOB" DATE NOT NULL, 
		"UP_ACTIVE_YN" CHAR(1 OCTETS) NOT NULL, 
		"UP_PWDEXPD" DATE NOT NULL, 
		"UP_DISABLED_YN" CHAR(1 OCTETS), 
		"UP_DISABLED_DATE" TIMESTAMP, 
		"UP_LAST_LOGIN_DATE" TIMESTAMP NOT NULL, 
		"UP_PWD_ATTEMPTS" SMALLINT NOT NULL, 
		"UPRRN" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		CONSTRAINT "SQL170831194408450" PRIMARY KEY
		("UP_USERID")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;
