CREATE TABLE "DB2ADMIN"."PWD_POLICY" (
		"PP_DAYS" SMALLINT NOT NULL, 
		"PP_NBR_UNIQUE" SMALLINT NOT NULL, 
		"PP_MAX_SIGNON_ATTEMPTS" SMALLINT NOT NULL, 
		"PP_PWD_MIN_LEN" SMALLINT NOT NULL, 
		"PP_UPPER_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_LOWER_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_NUMBER_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_SPECIAL_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_MAX_PWD_LEN" SMALLINT, 
		"PP_MAX_REPEAT_CHAR" SMALLINT, 
		"PP_NBR_DIGITS" SMALLINT, 
		"PP_NBR_UPPER" SMALLINT, 
		"PP_NBR_LOWER" SMALLINT, 
		"PP_NBR_SPECIAL" SMALLINT, 
		"PP_CANT_CONTAIN_ID" CHAR(5 OCTETS) NOT NULL, 
		"PP_CANT_CONTAIN_PWD" CHAR(5 OCTETS) NOT NULL, 
		"PP_RRN" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		CONSTRAINT "SQL200803170851700" PRIMARY KEY
		("PP_RRN")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

ALTER TABLE "DB2ADMIN"."PWD_POLICY" ADD CONSTRAINT "PP_LOWER_RQD_CHK" CHECK ( PP_LOWER_RQD ='y' OR PP_LOWER_RQD ='n' OR PP_LOWER_RQD ='Y' OR PP_LOWER_RQD ='N' );

ALTER TABLE "DB2ADMIN"."PWD_POLICY" ADD CONSTRAINT "PP_NUMBER_RQD_CHK" CHECK ( PP_NUMBER_RQD ='y' OR PP_NUMBER_RQD ='n' OR PP_NUMBER_RQD ='Y' OR PP_NUMBER_RQD ='N' );

ALTER TABLE "DB2ADMIN"."PWD_POLICY" ADD CONSTRAINT "PP_SPECIAL_RQD_CHK" CHECK ( PP_SPECIAL_RQD ='y' OR PP_SPECIAL_RQD ='n' OR PP_SPECIAL_RQD ='Y' OR PP_SPECIAL_RQD ='N' );

ALTER TABLE "DB2ADMIN"."PWD_POLICY" ADD CONSTRAINT "PP_UPPER_RQD_CHK" CHECK ( PP_UPPER_RQD ='y' OR PP_UPPER_RQD ='n' OR PP_UPPER_RQD ='Y' OR PP_UPPER_RQD ='N' );

ALTER TABLE "DB2ADMIN"."PWD_POLICY" ADD CONSTRAINT "PWD_POLICY_PP_CANT_CONTAIN_ID_CK" CHECK ( PP_CANT_CONTAIN_ID = 'y' OR PP_CANT_CONTAIN_ID = 'n' OR PP_CANT_CONTAIN_ID = 'Y' OR PP_CANT_CONTAIN_ID = 'N' );

ALTER TABLE "DB2ADMIN"."PWD_POLICY" ADD CONSTRAINT "PWD_POLICY_PP_CANT_CONTAIN_PWD_CK" CHECK ( PP_CANT_CONTAIN_PWD = 'y' OR PP_CANT_CONTAIN_PWD = 'n' OR PP_CANT_CONTAIN_PWD = 'Y' OR PP_CANT_CONTAIN_PWD = 'N' );

