CREATE TABLE "DB2ADMIN"."YARDISEQ" (
		"SEQNAME" VARCHAR(65 OCTETS) NOT NULL, 
		"SEQVALUE" BIGINT, 
		CONSTRAINT "SQL200709130528260" PRIMARY KEY
		("SEQNAME")
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;
