CREATE TABLE "DB2ADMIN"."PP_PWD_POLICY" (
		"PP_DAYS" SMALLINT NOT NULL, 
		"PP_NBR_UNIQUE" SMALLINT NOT NULL, 
		"PP_MAX_SIGNON_ATTEMPTS" SMALLINT NOT NULL, 
		"PP_PWD_MIN_LEN" SMALLINT NOT NULL, 
		"PP_UPPER_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_LOWER_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_NUMBER_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_SPECIAL_RQD" CHAR(5 OCTETS) NOT NULL, 
		"PP_RRN" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER )
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

ALTER TABLE "DB2ADMIN"."PP_PWD_POLICY" ADD CONSTRAINT "SQL170901172228550" PRIMARY KEY
	("PP_RRN");

