
CREATE TABLE "DB2ADMIN"."SESSIONS_TABLE" (
		"ST_USER_ID" VARCHAR(15 OCTETS) NOT NULL, 
		"ST_SESSSION_ID" VARCHAR(256 OCTETS) NOT NULL, 
		"ST_SESSION_TOKEN" CHAR(50 OCTETS) NOT NULL, 
		"ST_LAST_REQUEST" VARCHAR(256 OCTETS) NOT NULL, 
		"ST_LAST_ACTIVE" TIMESTAMP NOT NULL, 
		"ST_RRN" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER )
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE INDEX "DB2ADMIN"."SESSIONS_BY_USER"
	ON "DB2ADMIN"."SESSIONS_TABLE"
	("ST_USER_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

ALTER TABLE "DB2ADMIN"."SESSIONS_TABLE" ADD CONSTRAINT "SQL171121175248920" PRIMARY KEY
	("ST_SESSSION_ID");

