CREATE INDEX "DB2ADMIN"."SESSIONS_BY_USER"
	ON "DB2ADMIN"."SESSIONS_TABLE"
	("ST_USER_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

