CREATE TABLE "DB2ADMIN"."USER_GROUPS" (
		"UG_USER_ID" VARCHAR(15 OCTETS) NOT NULL, 
		"UG_GROUP" INTEGER NOT NULL, 
		"UG_RRN" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER )
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

CREATE INDEX "DB2ADMIN"."USER_GROUPS_BY_GROUP"
	ON "DB2ADMIN"."USER_GROUPS"
	("UG_GROUP"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

CREATE INDEX "DB2ADMIN"."USER_GROUPS_BY_USER_ID"
	ON "DB2ADMIN"."USER_GROUPS"
	("UG_USER_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;

ALTER TABLE "DB2ADMIN"."USER_GROUPS" ADD CONSTRAINT "SQL171121175252360" PRIMARY KEY
	("UG_RRN");

COMMENT ON TABLE "DB2ADMIN"."USER_GROUPS" IS
'Groups that each user belongs to';

